// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam/test/feature/auth/data/repository/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam/core/api/api_result.dart' as _i4;
import 'package:online_exam/feature/auth/data/datasource/auth_remote_datasource/auth_remote_data_source.dart'
    as _i2;
import 'package:online_exam/feature/auth/domain/entity/user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.User?>> register({
    required String? username,
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
    required String? rePassword,
    required String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #username: username,
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #password: password,
            #rePassword: rePassword,
            #phone: phone,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #username: username,
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
              #rePassword: rePassword,
              #phone: phone,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<String?>> forgetPassword({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [],
          {#email: email},
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #forgetPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<String?>> verifyResetCode(
          {required String? resetCode}) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [],
          {#resetCode: resetCode},
        ),
        returnValue: _i3.Future<_i4.Result<String?>>.value(
            _i6.dummyValue<_i4.Result<String?>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [],
            {#resetCode: resetCode},
          ),
        )),
      ) as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #email: email,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #email: email,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);
}
