// Mocks generated by Mockito 5.4.5 from annotations
// in online_exam/test/feature/home_layout/domain/use_case/explore/explore_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:online_exam/core/api/api_result.dart' as _i4;
import 'package:online_exam/feature/home_layout/data/mdoel/request/CheckQuestionsRequesrt.dart'
    as _i9;
import 'package:online_exam/feature/home_layout/data/mdoel/response/check_questions_model/CheckQuestionsModel.dart'
    as _i8;
import 'package:online_exam/feature/home_layout/data/mdoel/response/gel_all_exams_model/GetAllExamsModel.dart'
    as _i6;
import 'package:online_exam/feature/home_layout/data/mdoel/response/get_all_qeastions_model/Exam.dart'
    as _i10;
import 'package:online_exam/feature/home_layout/data/mdoel/response/get_all_qeastions_model/GetAllQuestionsModel.dart'
    as _i7;
import 'package:online_exam/feature/home_layout/data/mdoel/response/get_all_qeastions_model/Questions.dart'
    as _i11;
import 'package:online_exam/feature/home_layout/domain/repository/explore_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExploreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExploreRepository extends _i1.Mock implements _i2.ExploreRepository {
  MockExploreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<dynamic>> getAllSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, []),
            returnValue: _i3.Future<_i4.Result<dynamic>>.value(
              _i5.dummyValue<_i4.Result<dynamic>>(
                this,
                Invocation.method(#getAllSubjects, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<dynamic>>);

  @override
  _i3.Future<_i4.Result<_i6.GetAllExamsModel?>> getAllExams(
    String? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllExams, [subjectId]),
            returnValue: _i3.Future<_i4.Result<_i6.GetAllExamsModel?>>.value(
              _i5.dummyValue<_i4.Result<_i6.GetAllExamsModel?>>(
                this,
                Invocation.method(#getAllExams, [subjectId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.GetAllExamsModel?>>);

  @override
  _i3.Future<_i4.Result<_i7.GetAllQuestionsModel?>> getAllQuestions(
    String? examId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllQuestions, [examId]),
            returnValue:
                _i3.Future<_i4.Result<_i7.GetAllQuestionsModel?>>.value(
                  _i5.dummyValue<_i4.Result<_i7.GetAllQuestionsModel?>>(
                    this,
                    Invocation.method(#getAllQuestions, [examId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i7.GetAllQuestionsModel?>>);

  @override
  _i3.Future<_i4.Result<_i8.CheckQuestionsModel?>> checkQuestions(
    _i9.CheckQuestionsRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkQuestions, [request]),
            returnValue: _i3.Future<_i4.Result<_i8.CheckQuestionsModel?>>.value(
              _i5.dummyValue<_i4.Result<_i8.CheckQuestionsModel?>>(
                this,
                Invocation.method(#checkQuestions, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.CheckQuestionsModel?>>);

  @override
  _i3.Future<_i4.Result<void>> addExam(
    _i10.Exam? exam,
    List<_i11.Questions?>? questions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExam, [exam, questions]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#addExam, [exam, questions]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i10.Exam>>> getExamsList() =>
      (super.noSuchMethod(
            Invocation.method(#getExamsList, []),
            returnValue: _i3.Future<_i4.Result<List<_i10.Exam>>>.value(
              _i5.dummyValue<_i4.Result<List<_i10.Exam>>>(
                this,
                Invocation.method(#getExamsList, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i10.Exam>>>);
}
